#!/bin/bash

#This is the main processing script of the SV analysis output
#See pullVarVCF for details on the passed arguments 

echo "SV analysis started. Arguments are: Chr - $1, Start - $2, End - $3, ID - $4, Path - $5"

#Ensure all VCF files are compressed and indexed
./trav_bgzt $5

#Make the output directory
mkdir $5/pullVarVCF_output_$4

#Loop through files and run bcftools
for f in $(find $5 -name '*metasv.snpeff.vcf.gz' -or -name '*.vcf.gz.gz'); 
do 
    file=$(basename $f)
    echo "Analyzing $file" 
    bcftools query -i '((POS>='$2' & POS<='$3') | (INFO/END>='$2' & INFO/END<='$3')) & CHROM="chr$1"' -f '%CHROM\t%POS\t%REF\t%ALT\n' $f > "$5/pullVarVCF_output_$4/$file.pullvarvcf.$4"
done

#Count the number of variants per output file
printf "Analysis complete\nShowing counts per file.\n"
for f in $(ls "$5/pullVarVCF_output_$4"); 
do 
    wc -l $f 
done 
