#!/bin/bash

echo "MUGQIC analysis started. Arguments are: Chr - $1, Start - $2, End - $3, ID - $4, Path - $5"

#Run the single bcftools command for the large combined VCF file
bcftools query -i '((POS>='$2' & POS<='$3') | (INFO/END>='$2' & INFO/END<='$3')) & CHROM="chr'$1'"' -f '%SAMPLE\t%CHROM\t%POS\t%REF\t%ALT\n' $5 > "$5.MUGQIC.pullvarvcf.$4"

printf "Analysis completed"