#!/bin/bash

#This script relies on the gziptabix.sh script for greating bgzip'd VCF's and making an index for them
#Pass to this script the root directory of the subset of directories for which you would like to bgzip and index VCFs 
#For use with Compute Canada cluster's, tabix must be loaded 

for f in $(find $1 -name '*.vcf' -or -name '*germline.snpeff.vcf.gz'); 
do 
    ./gziptabix $f; 
done
